import localFont from "next/font/local";
import "../globals.css";
import MainHeader from "@/components/MainHeader";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cloakmate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
        <MainHeader/>
        <div className="grow bg-gradient-to-r from-[#eab308] to-[#1faed942]">
        {children}
        </div>
        </div>
        
      </body>
    </html>
  );
}
